export const GET_GAMELIST_REQUEST = "GET_GAMELIST_REQUEST";
export const GET_GAMELIST_SUCCESS = " GET_GAMELIST_SUCCESS";
export const GET_GAMELIST_FAIL = "GET_GAMELIST_FAIL";

export const GET_GAMESFILTER_REQUEST = "GET_GAMESFILTER_REQUEST";
export const GET_GAMESFILTER_SUCCESS = " GET_GAMESFILTER_SUCCESS";
export const GET_GAMESFILTER_FAIL = "GET_GAMESFILTER_FAIL";

export const GET_GAMEDETAILS_REQUEST = "GET_GAMEDETAILS_REQUEST";
export const GET_GAMEDETAILS_SUCCESS = " GET_GAMEDETAILS_SUCCESS";
export const GET_GAMEDETAILS_FAIL = "GET_GAMEDETAILS_FAIL";

export const GET_GAMESGENRELIST_REQUEST = "GET_GAMESGENRELIST_REQUEST";
export const GET_GAMESGENRELIST_SUCCESS = " GET_GAMESGENRELIST_SUCCESS";
export const GET_GAMESGENRELIST_FAIL = "GET_GAMESGENRELIST_FAIL";

export const GET_GAMEGENRES_REQUEST = "GET_GAMEGENRES_REQUEST";
export const GET_GAMEGENRES_SUCCESS = " GET_GAMEGENRES_SUCCESS";
export const GET_GAMEGENRES_FAIL = "GET_GAMEGENRES_FAIL";

export const GET_GAMEPLATFORMSNAME_REQUEST = "GET_GAMEPLATFORMSNAME_REQUEST";
export const GET_GAMEPLATFORMSNAME_SUCCESS = " GET_GAMEPLATFORMSNAME_SUCCESS";
export const GET_GAMEPLATFORMSNAME_FAIL = "GET_GAMEPLATFORMSNAME_FAIL";
