export const GET_GAMELIST_REQUEST = "GET_GAMELIST_REQUEST";
export const GET_GAMELIST_SUCCESS = " GET_GAMELIST_SUCCESS";
export const GET_GAMELIST_FAIL = "GET_GAMELIST_FAIL";

export const GET_GAMEDETAILS_REQUEST = "GET_GAMEDETAILS_REQUEST";
export const GET_GAMEDETAILS_SUCCESS = " GET_GAMEDETAILS_SUCCESS";
export const GET_GAMEDETAILS_FAIL = "GET_GAMEDETAILS_FAIL";

export const GET_GAMEPLATFORMS_REQUEST = "GET_GAMEPLATFORMS_REQUEST";
export const GET_GAMEPLATFORMS_SUCCESS = " GET_GAMEPLATFORMS_SUCCESS";
export const GET_GAMEPLATFORMS_FAIL = "GET_GAMEPLATFORMS_FAIL";
